[package]
name = "threejs-native-runtime"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
deno_core.workspace = true
deno_web.workspace = true
deno_webidl.workspace = true
deno_webgpu.workspace = true
thiserror.workspace = true

[dev-dependencies]
tokio.workspace = true
