[package]
name = "threejs-native-runtime"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
threejs-native-js-sources = { path = "../js-sources" }
deno_core.workspace = true
deno_web.workspace = true
deno_webidl.workspace = true
deno_webgpu.workspace = true
deno_image.workspace = true
deno_fetch.workspace = true
threejs-native-package = { path = "../package" }
deno_error.workspace = true
raw-window-handle.workspace = true
thiserror.workspace = true

[dev-dependencies]
tokio.workspace = true
